version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.21
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
    volumes:
      - esdata:/usr/share/elasticsearch/data
    command:
      - /bin/bash
      - -c
      - |
        bin/elasticsearch-plugin install --batch https://get.infini.cloud/elasticsearch/analysis-ik/7.17.21 || true
        exec /usr/local/bin/docker-entrypoint.sh eswrapper

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.21
    container_name: kibana
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch

volumes:
  esdata:
    driver: local

